### ISSUE TITLE
Error while opening

### ISSUE THREAD

**Issue by geckwwo** [Itzbenz/Minudstry-Hack#1]
Error while opening (Windows 10): 

 Error reading application id. Please either write it to steam_appid.txt or use the launcher.

What is this? This means that I need to buy Mindustry in the steam?

P.S. Sorry for my english, i'm russian

**Comment by Itzbenz** [comment]
[Disable Steam](https://github.com/Itzbenz/Minudstry-Oxygen-Client/commit/0eddf390a229a1fd0cb6cfe4ebf0ac540de513a9)
